#!/usr/bin/env bash

cf(){

    showUsage(){
        echo "usage: cf [directory]"
        echo
        echo "       /?        Show usage."
        

        return 0;
    }

    main(){
        [[ "$*" == *"/?"* ]] && showUsage && return 0;
        [[ $# -gt 1 ]] && showUsage && return 1;

        [[ $# -eq 0 ]] && cd "$OLDPWD" && return 0;

        return 0;
    }

    main "$@"
}

cf "$@"
