#!/usr/bin/env bash

cf(){

    showUsage(){
        echo "usage: cf [directory]"
        echo
        echo "       /?        Show usage."
        

        return 0;
    }

    changeDirectoryByPartialMatching(){
        local folders
        folders=("$1"/ "$1"*/ *"$1"/ *"$1"*/)

        for folder in "${folders[@]}"; do
            [[ -d "$folder" ]] && cd "$folder" && return 0;
        done

        return 1;
    }

    changeDirectoryByNumberDot(){
        echo "$1" | grep -E "^[1-9][0-9]*\\.$" 1>/dev/null || return 1;
        local i
        local path
        path=""
        for ((i=0; i<${1:0:-1}; i++)); do
            path="$path"../
        done
        cd "$path"
        return 0;
    }

    main(){
        [[ "$*" == *"/?"* ]] && showUsage && return 0;
        [[ $# -gt 1 ]] && showUsage && return 1;

        [[ $# -eq 0 ]] && cd "$OLDPWD" && return 0;

        changeDirectoryByPartialMatching "$1" && return 0;
        changeDirectoryByNumberDot "$1" && return 0;

        echo No such directory: "$1"
        return 1;
    }

    main "$@"
}

cf "$@"
