#!/usr/bin/env bash

clip(){

    showUsage(){
        local scriptFileBaseName
        scriptFileBaseName=$(basename "$0")
        echo "usage: $scriptFileBaseName file"
        echo
        echo "       /?        Show usage."
        echo
        echo "       Copy a file or directory to clipboard."
        echo
        return 0;
    }

    copyFileToClipBoard(){
        osascript \
            -e 'on run {a}' \
            -e 'set the clipboard to POSIX file (POSIX path of ((POSIX file a) as alias))' \
            -e 'end' \
            "$1" 2> /dev/null
    }

    main(){
        [[ $# -eq 0 ]] && showUsage && return 1;
        [[ "$*" == *"/?"* ]] && showUsage && return 0;

        copyFileToClipBoard "$1"

        return 0;
    }

    main "$@"
}

clip "$@"
