#!/usr/bin/env bash

action(){

    showUsage(){
        echo "show usage."

        return 0;
    }

    main(){
        [[ $# -eq 0 ]] && showUsage && return 1;
        [[ "$*" =~ "/?" ]] && showUsage && return 0;

        return 0;
    }

    main "$@"
}

action "$@"
