#!/usr/bin/env bash

cre(){

    showUsage(){
        echo "usage: cre [/x:ext] file [...]"
        echo
        echo "       /?        Show usage."
        echo "       /x:ext    'ext' is used to filter template file, which is latter part of template file name."
        echo
        echo "       All template files are in 'template' directory, which is in this script file's parent direcory."
        echo
        return 0;
    }

    getScriptDirectory(){
        cd "$(dirname "$0")" && pwd
        return 0;
    }

    createTemplateFile(){
        

        local file
        local templateFile
        local fileDir
        local fileName
        local fileBaseName
        local fileExtension
        
        file="$1"

        [[ -a "$file" ]] && echo Exist such file or directory: "$file" && return 0;

        fileDir=$(dirname "$file")
        fileName=$(basename "$file")
        fileBaseName=${fileName%.*}
        
        [[ ! -a "$fileDir" ]] && mkdir -p "$fileDir"
        
        if [[ "$fileName" = "$fileBaseName" ]]; then
            touch "$file"
            return 0;
        fi

        fileExtension=${fileName##*.}            
        templateFile=$(getScriptDirectory)/template/template"$2"."$fileExtension"
        
        if [[ -a "$templateFile" ]]; then
            cp "$templateFile" "$file"
        else
            touch "$file"
        fi
        return 0;
    }

    main(){
        [[ $# -eq 0 ]] && showUsage && return 1;
        [[ "$*" =~ "/?" ]] && showUsage && return 0;

        local args
        local ext

        if [[ "${1:0:3}" = "/x:" ]]; then
            args=( "${@:2}" )
            ext="${1:3}"
        else
            args=( "$@" )
            ext=""
        fi

        for file in "${args[@]}"; do
            createTemplateFile "$file" "$ext"
        done

        return 0;
    }
    
    main "$@"
}

cre "$@"