#!/usr/bin/env bash

to(){

    showUsage(){
        echo "usage: to [key]"
        echo
        echo "       /?        Show usage."
        echo "       key       It's the 'key' of key-value or the front part of the 'key'."
        echo
        echo "       It will show all key-value when the arguments is empty."

        return 0;
    }

    changeDirectory(){
        local targetDir
        targetDir=$(path "$1")

        if [[ "$targetDir" == "" ]]; then
            echo No such key: "$1"
        else
            targetDir="${targetDir#*=}"
            if [[ -d "$targetDir" ]]; then
                cd "$targetDir"
            else
                targetDir=$(dirname "${targetDir#*=}")
                cd "$targetDir"
            fi
        fi
    }

    main(){
        
        [[ $# -eq 0 ]] && path && return 0;
        [[ "$*" == *"/?"* ]] && showUsage && return 0;
        [[ $# -gt 1 ]] && showUsage && return 1;

        changeDirectory "$1"

        return 0;
    }

    main "$@"
}

to "$@"
