#!/usr/bin/env bash

to(){

    showUsage(){
        local scriptFileBaseName
        scriptFileBaseName=$(basename "$0")
        echo "usage: $scriptFileBaseName "
        echo
        echo "       /?        Show usage."
        

        return 0;
    }

    changeDirectory(){
        local targetDir
        targetDir=$(path "$1")

        if [[ "$targetDir" == "" ]]; then
            echo No such key: "$1"
        else
            targetDir="${targetDir#*=}"
            if [[ -d "$targetDir" ]]; then
                cd "$targetDir"
            else
                targetDir=$(dirname "${targetDir#*=}")
                cd "$targetDir"
            fi
        fi
    }

    main(){
        
        [[ $# -eq 0 ]] && path && return 0;
        [[ "$*" == *"/?"* ]] && showUsage && return 0;
        [[ $# -gt 1 ]] && showUsage && return 1;

        changeDirectory "$1"

        return 0;
    }

    main "$@"
}

to "$@"
